version: '2'
services:
  tomcat:
    env_file: envs
    image: tutum/tomcat:7.0
    ports:
      - "8089:8089"
      - "8088:8088"
      - "8081:8080"
    networks:
      - front-tier
networks:
  front-tier: