version: '2'
services:
  tomcat:
    env_file: envs
    build: src/test/resources/tomcat
    ports:
      - "8090:8089"
      - "8088:8088"
      - "8080:8080"
    networks:
      - front-tier
networks:
  front-tier:
