tomcat:
  env_file: envs
  build: ./src/test/resources/tomcat
  ports:
      - "8089:8089"
      - "8088:8088"
      - "8081:8080"
  links:
      - pingpong:pingpong

pingpong:
  image: jonmorehouse/ping-pong
  ports:
      - "8080:8080"
