= Arquillian Cube
:asciidoctor-source: https://raw.githubusercontent.com/arquillian/arquillian-cube/master/docs

Documentation for version Alpha6 can be found here: https://github.com/arquillian/arquillian-cube/blob/1.0.0.Alpha6/README.adoc

Documentation for version Alpha5 can be found here: https://github.com/arquillian/arquillian-cube/blob/1.0.0.Alpha5/README.adoc

Documentation for version Alpha4 can be found here: https://github.com/arquillian/arquillian-cube/blob/1.0.0.Alpha4/README.adoc


WARNING: 1.0.0.Alpha7 breaks incompatibility with previous versions in some cases. The major difference is that instead of using the _boot2docker_ keyword to refer to the auto resolved boot2docker ip in the _serverUri_ parameter, you should now used _dockerHost_.

IMPORTANT: If you are using Docker 1.11 or beyond you will need to set explicitly the configuration property `serverVersion` to `1.23`. This is because of requirement of `docker-java` (https://github.com/docker-java/docker-java/issues/617#issuecomment-237825886).

include::{asciidoctor-source}/what-is-this.adoc[]

include::{asciidoctor-source}/preliminaries.adoc[]

include::{asciidoctor-source}/example.adoc[]

include::{asciidoctor-source}/configuration.adoc[]

include::{asciidoctor-source}/boot2docker-dockermachine.adoc[]

include::{asciidoctor-source}/build-containers.adoc[]

include::{asciidoctor-source}/compose.adoc[]

include::{asciidoctor-source}/enrichers.adoc[]

include::{asciidoctor-source}/cop.adoc[]

include::{asciidoctor-source}/containerless.adoc[]

include::{asciidoctor-source}/drone.adoc[]

include::{asciidoctor-source}/reports.adoc[]

include::{asciidoctor-source}/polyglot.adoc[]

== Future work

API will continuously evolve to fit requirements of an enterprise application as well as providing integration with _Kubernates_ and other Docker related tools.
Also some configuration parameters will be modified to fix any possible requirements.
Although we are going to try to not break compatibility with previous versions, we cannot guarantee until _beta_ stage.

Feel free to use it and any missing feature, bug or anything you see , feel free to add a new issue.
